# Port
server:
  port: 10000

# JPA
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  main:
    allow-bean-definition-overriding: true

#  spring:
#    security:
#      oauth2:
#        client:
##          registration:
##            google:
##              clientId:
###              clientSecret:
##              scope:
##                - email
##                - profile
#          provider:
#            google:
#              authorizationUri: https://accounts.google.com/o/oauth2/auth
#              tokenUri: https://oauth2.googleapis.com/token
#              userInfoUri: https://openidconnect.googleapis.com/v1/userinfo
#              userNameAttribute: sub